### PR TITLE
add download function + correct xlsx download

### PR DESCRIPTION
**Pull request by kjwinfield**
Add functionality to download output xlsx workbooks to clingen.
Correct process to get output xlsx so it gets the correct file ID
Test workbooks have been added:
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4)* status: all files reviewed, 3 unresolved discussions (waiting on @kjwinfield)

___
*[`README.md` line 24 at r2](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-O3XRTIE9pmwApS9-MMo:-O3XRTIF1iSK5aSLJUvl:b-c7y9uu) ([raw file](https://github.com/eastgenomics/rd_wgs_workbooks_monitoring/blob/ecf04021999c5ff5332cca189fea3f26a959bad7/README.md#L24)):*
> ```Markdown
> **Inputs (optional)**:
> * `--testing`: if specified, will run first 5 records in database only.
> * `--download`: if specified, will download workbooks to clingen in the folder `//clingen/cg/Regional Genetics Laboratories\Molecular Genetics\Data archive\Sequencing HT\WGS_automated`
> ```

/ / / / \ \ \ \

Mixed forward/back slash



_Code quote:_
```Markdown
//clingen/cg/Regional Genetics Laboratories\Molecular Genetics\Data archive\Sequencing HT\WGS_automated
```
___
*[`rd_wgs_workbooks_monitor.py` line 35 at r2](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-O3XT-9r3QejuWsj0veY:-O3XT-9r3QejuWsj0veZ:bm47qi7) ([raw file](https://github.com/eastgenomics/rd_wgs_workbooks_monitoring/blob/ecf04021999c5ff5332cca189fea3f26a959bad7/rd_wgs_workbooks_monitor.py#L35)):*
> ```Python
>     )
>     parser.add_argument(
>         "--download", action=argparse.BooleanOptionalAction,
> ```

Would it be better if this took a path as an argument rather than being a bool? 

That way if we move things on clingen we don't have to update this app



_Code quote:_
```Python
--download
```
___
*[`rd_wgs_workbooks_monitor.py` line 38 at r2](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-O3XRphg3bTdU-6RBNHq:-O3XRphg3bTdU-6RBNHr:bt1qrq1) ([raw file](https://github.com/eastgenomics/rd_wgs_workbooks_monitoring/blob/ecf04021999c5ff5332cca189fea3f26a959bad7/rd_wgs_workbooks_monitor.py#L38)):*
> ```Python
>         help="If set to true will download workbooks to clingen in the folder"
>         "//clingen/cg/Regional Genetics Laboratories\Molecular Genetics\Data "
>         "archive\Sequencing HT\WGS_automated"
> ```

/ / / / \ \ \ \ 



_Code quote:_
```Python
        "//clingen/cg/Regional Genetics Laboratories\Molecular Genetics\Data "
        "archive\Sequencing HT\WGS_automated"
```

**Review by kjwinfield — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-:-O3XhAuu4VA2KJzLN8nF:bnfp4nl)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[`README.md` line 24 at r2](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-O3XRTIE9pmwApS9-MMo:-O3XhCjv4ZceG9Y3gulD:b-18axls) ([raw file](https://github.com/eastgenomics/rd_wgs_workbooks_monitoring/blob/ecf04021999c5ff5332cca189fea3f26a959bad7/README.md#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

/ / / / \ \ \ \

Mixed forward/back slash
</blockquote></details>

Done. Path is now input by user
___
*[`rd_wgs_workbooks_monitor.py` line 35 at r2](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-O3XT-9r3QejuWsj0veY:-O3XhJk93lKQdkDE9f5t:b-896fix) ([raw file](https://github.com/eastgenomics/rd_wgs_workbooks_monitoring/blob/ecf04021999c5ff5332cca189fea3f26a959bad7/rd_wgs_workbooks_monitor.py#L35)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Would it be better if this took a path as an argument rather than being a bool? 

That way if we move things on clingen we don't have to update this app
</blockquote></details>

Done.
___
*[`rd_wgs_workbooks_monitor.py` line 38 at r2](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4#-O3XRphg3bTdU-6RBNHq:-O3XhLYWA0d6fwSnGWY6:b-18axls) ([raw file](https://github.com/eastgenomics/rd_wgs_workbooks_monitoring/blob/ecf04021999c5ff5332cca189fea3f26a959bad7/rd_wgs_workbooks_monitor.py#L38)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

/ / / / \ \ \ \
</blockquote></details>

Done. Path is now input by user

**Comment by kjwinfield** [comment]
Database is updated:
image
File is on clingen:
image

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/rd_wgs_workbooks_monitoring/4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)

**Pull request merged**
